/* eslint-disable */
/**
 * Generated by convex dev. Will be replaced when Convex is initialized.
 */
import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as reviews from "../reviews.js";
import type * as clauses from "../clauses.js";

declare const fullApi: ApiFromModules<{
  reviews: typeof reviews;
  clauses: typeof clauses;
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
