/* eslint-disable */
/**
 * Generated by convex dev. Will be replaced when Convex is initialized.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
