/* eslint-disable */
/**
 * Generated by convex dev. Will be replaced when Convex is initialized.
 */
import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type Id<T extends string> = string & { __tableName: T };
