/* eslint-disable */
/**
 * Generated by convex dev. Will be replaced when Convex is initialized.
 */
import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
} from "convex/server";

export const query = queryGeneric;
export const internalQuery = queryGeneric;
export const mutation = mutationGeneric;
export const internalMutation = mutationGeneric;
export const action = actionGeneric;
export const internalAction = actionGeneric;
